### PR TITLE
Repository protocol extension

### PR DESCRIPTION
**Pull request by jmnavarro**

### CODE REVIEW

**Comment by ziogaschr** [comment]
@jmnavarro thanks for contributing this, although I am not sure that this extension really helps.

The intention of the protocol is to let the developer knows that he has to implement this based on his needs (for the project I am using this library the `!==nil` check is not enough). Probably, some developers will miss this functionality as it is camouflaged now and they will start opening new issues for no reason.

Although, I can see your intention for making this awesome library easier to be integrated in a project :+1:,  with that being said, if everyone agrees that your PR will work for most cases then let's merge it.

Thanks for sharing it ;)

**Comment by ZachJiroun** [comment]
This pull request breaks the demo app code. I still had to implement hasPasscode in order to conform to the PasscodeRepositoryType protocol, so not sure this code change is necessary.

**Comment by jmnavarro** [comment]
@ziogaschr I understand your point, no problem if you consider to close the PR (I see it merged though)

**Comment by ziogaschr** [comment]
@jmnavarro I am very happy that you took the time to make this PR and to see that this repo is being used :+1:  . @yankodimitrov did a great job. Although let's consider all together if this PR will help, and if not we can revert it.

**Comment by velikanov** [comment]
guys, let's link some testing engine to our repo
we have to know what's happening with the project after every PR and update tests or refusing PRs

**Comment by ziogaschr** [comment]
Good point @velikanov. The demo code is broken because of this PR, I will revert it. Let me know if you want it back.

**Pull request merged**
